fix

diff --git a/.github/workflows/deploy_docker_img_to_ec2.yml b/.github/workflows/deploy_docker_img_to_ec2.yml
--- a/.github/workflows/deploy_docker_img_to_ec2.yml
+++ b/.github/workflows/deploy_docker_img_to_ec2.yml
@@ -18,7 +18,7 @@ jobs:
 
     steps:
       - name: Checkout Repository Code
-        uses: actions/checkout@v7
+        uses: actions/checkout@v4
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -29,20 +29,18 @@ jobs:
       - name: Fetch EC2 Information
         id: ec2_data
         run: |
-          # Fetch instances matching a specific tag (e.g., Name=MyWebServer)
-          INSTANCE_JSON=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=${{secrets.AWS_EC2_INSTANCE_NAME}}" \
+          set -e
+          
+          # Query AWS for instances matching the Name tag
+          INSTANCE_ID=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name,Values=${{ secrets.AWS_EC2_INSTANCE_NAME }}" "Name=instance-state-name,Values=running" \
               --query "Reservations[*].Instances[*].InstanceId" \
               --output text)
 
-          # Write directly to the GitHub Output stream
-          echo "ec2_instance_id=$INSTANCE_JSON" >> "$GITHUB_OUTPUT"
-          echo "Found Instance ID: $INSTANCE_JSON , $GITHUB_OUTPUT"
-
-          # if [ -z "$INSTANCE_ID" ]; then
-          #   echo "::error::No running EC2 instance found matching tag Name='${{ secrets.AWS_EC2_INSTANCE_NAME }}'."
-          #   exit 1
-          # fi
+          if [ -z "$INSTANCE_ID" ]; then
+            echo "::error::No running EC2 instance found matching tag Name='${{ secrets.AWS_EC2_INSTANCE_NAME }}'."
+            exit 1
+          fi
 
           echo "Found Instance ID: $INSTANCE_ID"
           echo "ec2_instance_id=$INSTANCE_ID" >> "$GITHUB_OUTPUT"
@@ -66,7 +64,7 @@ jobs:
 
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v7
+        uses: actions/checkout@v4
 
       - name: Configure AWS Credentials via OIDC
         uses: aws-actions/configure-aws-credentials@v4
