fix:::

diff --git a/.github/workflows/deploy_docker_img_to_ec2.yml b/.github/workflows/deploy_docker_img_to_ec2.yml
--- a/.github/workflows/deploy_docker_img_to_ec2.yml
+++ b/.github/workflows/deploy_docker_img_to_ec2.yml
@@ -39,10 +39,10 @@ jobs:
           echo "ec2_instance_id=$INSTANCE_JSON" >> "$GITHUB_OUTPUT"
           echo "Found Instance ID: $INSTANCE_JSON , $GITHUB_OUTPUT"
 
-          if [ -z "$INSTANCE_ID" ]; then
-            echo "::error::No running EC2 instance found matching tag Name='${{ secrets.AWS_EC2_INSTANCE_NAME }}'."
-            exit 1
-          fi
+          # if [ -z "$INSTANCE_ID" ]; then
+          #   echo "::error::No running EC2 instance found matching tag Name='${{ secrets.AWS_EC2_INSTANCE_NAME }}'."
+          #   exit 1
+          # fi
 
           echo "Found Instance ID: $INSTANCE_ID"
           echo "ec2_instance_id=$INSTANCE_ID" >> "$GITHUB_OUTPUT"
